mobile nav
cbaron/FutureDaysWebsite pull request #7
Opened 2020-03-18 18:32 UTC by JamesKemp296

2020-03-18 18:33 UTC, JamesKemp296 commented
![Screenshot from 2020-03-18 14-32-37](https://user-images.githubusercontent.com/16766024/76994871-67899e00-6925-11ea-9568-bea3b2556b7f.png)
![Screenshot from 2020-03-18 14-32-46](https://user-images.githubusercontent.com/16766024/76994873-68223480-6925-11ea-99cb-57dc355c3ce4.png)

2020-03-18 20:46 UTC, cbaron commented on apps/webClient/src/components/MobileNav/index.tsx
> +  children: ReactNode;
`Props` should be empty as we don't use any props If I read this correctly.

2020-03-18 20:48 UTC, cbaron commented on apps/webClient/src/components/View/index.tsx
> -  children: React.ReactNode;
Not sure what the confusion is here - we _do_ use `children` in this component.

2020-03-18 20:49 UTC, cbaron requested changes
Very nice.  Just a concern on the component prop interface declarations

2020-03-19 15:32 UTC, cbaron approved these changes

2020-03-19 16:35 UTC, merged